window.STORYBOARD_SHOTS = [
  {
    "uid": "shot-001",
    "id": 1,
    "chapter": "篇章一｜强强联手·战略启航",
    "image": "images/001_渤海海面.jpg",
    "customImage": "",
    "duration": 2.0,
    "location": "渤海海面",
    "method": "实拍航拍",
    "shotSize": "大全景",
    "voiceover": "渤海潮涌，津门向新！千年商脉奔流不息，",
    "camera": "固定",
    "description": "【实景】渤海日出，金色阳光从地平线升起并铺洒海面；海面保留晨雾与金色潮纹，建立“渤海潮涌”的恢弘开场。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "固定",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "网络图片",
    "sourcePage": "https://bbs.zol.com.cn/dcbbs/d22_84150.html",
    "sourceNote": "成山头海上日出（网络参考）"
  },
  {
    "uid": "shot-002",
    "id": 2,
    "chapter": "篇章一｜强强联手·战略启航",
    "image": "images/002_天津港外海.jpg",
    "customImage": "",
    "duration": 3.0,
    "location": "天津港外海",
    "method": "实拍航拍/版权",
    "shotSize": "大全景",
    "voiceover": "时代浪潮浩荡向前。天津，京津冀协同发展核心引擎，",
    "camera": "跟随",
    "description": "【实景】天津港外海，一艘巨轮缓缓驶出港区。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "跟随",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "网络图片",
    "sourcePage": "https://www.seetaoe.com/details/201576.html",
    "sourceNote": "天津港集装箱船与码头（网络参考）"
  },
  {
    "uid": "shot-003",
    "id": 3,
    "chapter": "篇章一｜强强联手·战略启航",
    "image": "images/003_天津港码头.jpg",
    "customImage": "",
    "duration": 3.0,
    "location": "天津港码头",
    "method": "实拍/版权",
    "shotSize": "大远景",
    "voiceover": "北方国际航运核心区，",
    "camera": "固定 → 跟随",
    "description": "【连续画面】1、天津港繁忙景象，桥吊完成一次集装箱起吊；2、集装箱离开堆场并升入画面，港口装卸作业",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "固定 → 跟随",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "网络图片",
    "sourcePage": "https://info.chineseshipping.com.cn/cninfo/News/202307/t20230718_1379145.shtml",
    "sourceNote": "天津港桥吊集装箱作业（网络参考）"
  },
  {
    "uid": "shot-004",
    "id": 4,
    "chapter": "篇章一｜强强联手·战略启航",
    "image": "images/004_滨海机场.jpg",
    "customImage": "",
    "duration": 3.0,
    "location": "滨海机场",
    "method": "实拍/版权",
    "shotSize": "特写 → 全景",
    "voiceover": "陆海丝路在此交汇——一座城市的雄心与国家的战略，",
    "camera": "跟随",
    "description": "【连续画面】1、侧 一架货机从跑道离地并进入天空；2、正 一架货机从跑道离地并进入天空",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "跟随",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-005",
    "id": 5,
    "chapter": "篇章一｜强强联手·战略启航",
    "image": "images/005_天津城市天际线.jpg",
    "customImage": "",
    "duration": 4.0,
    "location": "天津城市天际线",
    "method": "实拍航拍/延时",
    "shotSize": "特写 → 大全景",
    "voiceover": "在此同频共振！",
    "camera": "固定",
    "description": "【连续画面】1、某高层楼顶 太阳从后方升起 天津城市天际线由暗转明，从蓝调时刻过渡至晨光；2、天津城市天际线由暗转明，从蓝调时刻过渡至晨光",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "固定",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-006",
    "id": 6,
    "chapter": "篇章一｜强强联手·战略启航",
    "image": "images/006_虚拟品牌空间 → 项目主视觉.jpg",
    "customImage": "",
    "duration": 4.0,
    "location": "虚拟品牌空间 → 项目主视觉",
    "method": "MG/合成 / MG/3D",
    "shotSize": "大全景 → 特写→中景",
    "voiceover": "正扬帆起航，破浪前行——天津国际农产品交易中心！",
    "camera": "无 → 粒子收拢",
    "description": "【连续画面】1、天津食品集团与首衡集团双LOGO从画面两侧进入；2、【虚拟包装】金色粒子光效由四周汇聚，逐渐组成项目LOGO与“天津国际农产品交易中心”标准名称；背景为天津城市剪影。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "无 → 粒子收拢",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-007",
    "id": 7,
    "chapter": "篇章一｜强强联手·战略启航",
    "image": "images/007_滨海临港地图 → 项目地块.jpg",
    "customImage": "",
    "duration": 4.0,
    "location": "滨海临港地图 → 项目地块",
    "method": "三维地图/MG",
    "shotSize": "俯视大全景 → 中远景",
    "voiceover": "天津食品集团，这座城市的民生守护者；首衡集团，全国农产品流通的领军力量。当深耕民生的赤子情怀，遇上贯通南北的磅礴格局，",
    "camera": "垂直缓推 → 轻推",
    "description": "【连续画面】1、【虚拟三维地图】天津滨海临港区域进入画面，项目地块红线高亮闪烁；周边城市、港口与交通关系保持可辨识。；2、【虚拟三维地图】项目全称定位针从红线地块中心弹出，“天津国际农产品交易中心”名称与落位点清晰锁定。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "垂直缓推 → 轻推",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-008",
    "id": 8,
    "chapter": "篇章一｜强强联手·战略启航",
    "image": "images/008_天津区域示意 → 合作锁定画面.jpg",
    "customImage": "",
    "duration": 4.0,
    "location": "天津区域示意 → 合作锁定画面",
    "method": "MG",
    "shotSize": "大全景 → 中景",
    "voiceover": "两大巨擘并肩而立，以山河为卷、以使命为笔，共绘城市级民生产业的恢弘蓝图！",
    "camera": "信息聚焦 → 静稳",
    "description": "【连续画面】1、【动态图文】天津区域轮廓上突出“天津唯一大型综合性农产品批发市场”信息卡，项目位置同步保留，强化差异化认知。；2、【虚拟包装】天津食品集团×首衡集团联合标识与项目名称同屏定格，画面形成“市属国企 × 全国农批龙头｜强强合资”的完整落版。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "信息聚焦 → 静稳",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-009",
    "id": 9,
    "chapter": "篇章一｜强强联手·战略启航",
    "image": "images/009_项目主入口.jpg",
    "customImage": "",
    "duration": 3.0,
    "location": "项目主入口",
    "method": "3D渲染",
    "shotSize": "中近景",
    "voiceover": "顺应国家港产城融合发展大势，合力落子滨海临港。",
    "camera": "弧形环绕",
    "description": "【3D渲染】项目主入口大门环绕特写；清晨金色侧光勾勒门头、标识与建筑材质，主入口完整、庄重地第一次亮相。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "弧形环绕",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-010",
    "id": 10,
    "chapter": "篇章一｜强强联手·战略启航",
    "image": "images/010_园区主干道.jpg",
    "customImage": "",
    "duration": 4.0,
    "location": "园区主干道",
    "method": "3D渲染",
    "shotSize": "大全景",
    "voiceover": "这不是一次普通的布局，而是一次面向未来的战略落子——打造全市唯一超大型综合性农产品交易枢纽，",
    "camera": "低机位前移",
    "description": "【3D渲染】镜头越过项目大门进入园区主干道，清晨园区全景缓缓浮现；道路向纵深延伸，远处建筑形成明确消失点。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "低机位前移",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-011",
    "id": 11,
    "chapter": "篇章一｜强强联手·战略启航",
    "image": "images/011_交易建筑组团.jpg",
    "customImage": "",
    "duration": 5.0,
    "location": "交易建筑组团",
    "method": "3D渲染",
    "shotSize": "远景",
    "voiceover": "锚定国家级产业平台定位，",
    "camera": "侧向滑轨",
    "description": "【3D渲染】交易大厅、厂房与冷库建筑组团在晨光中横向展开，建筑轮廓完整铺开；飞鸟从建筑上方掠过。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "侧向滑轨",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-012",
    "id": 12,
    "chapter": "篇章一｜强强联手·战略启航",
    "image": "images/012_园区全景.jpg",
    "customImage": "",
    "duration": 6.0,
    "location": "园区全景",
    "method": "3D渲染",
    "shotSize": "超大全景",
    "voiceover": "以时代之名，立下产业报国的铮铮誓言！",
    "camera": "航拍拉升",
    "description": "【3D渲染】镜头航拍拉升至园区鸟瞰，道路、厂房、冷库与车流如织的运营景象共同构成完整产业新城版图。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "航拍拉升",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-013",
    "id": 13,
    "chapter": "篇章二｜规模定位·时代枢纽",
    "image": "images/013_京津冀地图.jpg",
    "customImage": "",
    "duration": 4.0,
    "location": "京津冀地图",
    "method": "三维地图",
    "shotSize": "俯视大全景",
    "voiceover": "雄踞京津冀核心地带，空、海、公、铁四维多式联运无缝衔接。对内直达城乡腹地，",
    "camera": "下钻 → 固定",
    "description": "【连续画面】1、【虚拟三维地图】从中国北方下钻至京津冀核心地带，项目为中心的50km圈层首先亮起，建立区域核心坐标。；2、【虚拟三维地图】150km与300km辐射圈层由项目向外分层扩散，清晰呈现服务京津冀、辐射更广区域的空间范围。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "下钻 → 固定",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-014",
    "id": 14,
    "chapter": "篇章二｜规模定位·时代枢纽",
    "image": "images/014_公路网络.jpg",
    "customImage": "",
    "duration": 2.0,
    "location": "公路网络",
    "method": "三维地图",
    "shotSize": "俯视中景",
    "voiceover": "血脉畅通；对外连通全球航线，",
    "camera": "沿线追踪",
    "description": "【虚拟三维地图】京沪高速、港城大道及周边公路线路由项目点向外发光流动，车辆光点沿道路运行，表现公路网络畅通。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "沿线追踪",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-015",
    "id": 15,
    "chapter": "篇章二｜规模定位·时代枢纽",
    "image": "images/015_铁路网络.jpg",
    "customImage": "",
    "duration": 2.0,
    "location": "铁路网络",
    "method": "三维地图",
    "shotSize": "俯视中景",
    "voiceover": "拥抱世界。这里是天然的跨境流通枢纽，",
    "camera": "沿线追踪",
    "description": "【虚拟三维地图】铁路线路亮起并沿线追踪至滨海西站，站点独立弹出“距滨海西站5km”动态信息卡。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "沿线追踪",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-016",
    "id": 16,
    "chapter": "篇章二｜规模定位·时代枢纽",
    "image": "images/016_滨海机场 → 天津港.jpg",
    "customImage": "",
    "duration": 5.0,
    "location": "滨海机场 → 天津港",
    "method": "三维地图",
    "shotSize": "俯视中景 → 俯视中景→大全景",
    "voiceover": "是京津冀面向全球的门户，是时代赋予的黄金坐标！",
    "camera": "定位聚焦 → 轻拉远",
    "description": "【连续画面】1、【虚拟三维地图】滨海机场图标亮起，项目至机场的连线完成生长并标注“距机场30km”，呈现空运连接。；2、【虚拟三维地图】天津港节点亮起并标注“距港17km”；空、海、公、铁线路最终同屏汇总，形成四维多式联运网络。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "定位聚焦 → 轻拉远",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-017",
    "id": 17,
    "chapter": "篇章二｜规模定位·时代枢纽",
    "image": "images/017_园区总平.jpg",
    "customImage": "",
    "duration": 4.0,
    "location": "园区总平",
    "method": "3D渲染",
    "shotSize": "顶视大全景",
    "voiceover": "项目总占地1545亩，地上总建面75万㎡，",
    "camera": "垂直拉升 → 固定",
    "description": "【连续画面】1、【4K三维渲染】1545亩园区总平全景垂直拉升，项目地块边界线逐段描出，“1545亩”核心数字随边界完成而出现。；2、【4K三维渲染】园区总平保持俯视，一期、二期用地色块分层弹出并依次点亮，明确呈现“分两期有序开发”。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "垂直拉升 → 固定",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-018",
    "id": 18,
    "chapter": "篇章二｜规模定位·时代枢纽",
    "image": "images/018_园区建筑.jpg",
    "customImage": "",
    "duration": 2.0,
    "location": "园区建筑",
    "method": "3D渲染",
    "shotSize": "鸟瞰",
    "voiceover": "总投资51亿元，分两期有序开发。",
    "camera": "建筑生长",
    "description": "【4K三维渲染】建筑体量从园区地面逐层生长，交易建筑、冷库及配套组团由白模过渡至完整材质。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "建筑生长",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-019",
    "id": 19,
    "chapter": "篇章二｜规模定位·时代枢纽",
    "image": "images/019_建筑群 → 园区全景.jpg",
    "customImage": "",
    "duration": 6.0,
    "location": "建筑群 → 园区全景",
    "method": "3D+包装",
    "shotSize": "大全景 → 超大全景",
    "voiceover": "超大体量规划，不仅是数字的累积，更是雄心的丈量！",
    "camera": "缓推 → 轻拉远",
    "description": "【连续画面】1、【4K三维渲染+数据包装】完整建筑群稳定呈现，画面只突出“地上总建面75万㎡”大字报，数字与园区体量对应。；2、【4K三维渲染+数据包装】园区全景轻拉远，“总投资51亿元”在稳定画面上弹出，与1545亩、75万㎡共同完成规模信息。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "缓推 → 轻拉远",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-020",
    "id": 20,
    "chapter": "篇章二｜规模定位·时代枢纽",
    "image": "images/020_资质文件.jpg",
    "customImage": "",
    "duration": 2.0,
    "location": "资质文件",
    "method": "甲方文件+包装",
    "shotSize": "特写",
    "voiceover": "获评市级重点工程、“十五五”核心规划载体，",
    "camera": "缓推",
    "description": "【甲方文件+虚拟包装】天津市重点项目相关文件局部进入画面，“天津市重点项目/市级重点工程”关键词以金色高亮。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "缓推",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-021",
    "id": 21,
    "chapter": "篇章二｜规模定位·时代枢纽",
    "image": "images/021_规划文件.jpg",
    "customImage": "",
    "duration": 2.0,
    "location": "规划文件",
    "method": "甲方文件+包装",
    "shotSize": "特写",
    "voiceover": "多重官方资质加持——当以标杆之姿，",
    "camera": "缓推",
    "description": "【甲方文件+虚拟包装】“十五五”相关规划文件局部翻转出现，项目名称及“规划项目/核心规划载体”关键词被重点标注。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "缓推",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-022",
    "id": 22,
    "chapter": "篇章二｜规模定位·时代枢纽",
    "image": "images/022_示范材料 → 资质汇总.jpg",
    "customImage": "",
    "duration": 6.0,
    "location": "示范材料 → 资质汇总",
    "method": "甲方文件+包装 / MG",
    "shotSize": "特写 → 中景",
    "voiceover": "立时代潮头！旁白跨镜延续 / 音乐承接",
    "camera": "缓推 → 三卡并列",
    "description": "【连续画面】1、【甲方文件+虚拟包装】港产城融合相关材料局部出现，“港产城融合”“示范/标杆”关键词依次高亮。；2、【虚拟包装】天津市重点项目、“十五五”规划项目、港产城融合标杆三张金色资质卡片并列，统一完成一次庄重盖印。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "缓推 → 三卡并列",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-023",
    "id": 23,
    "chapter": "篇章二｜规模定位·时代枢纽",
    "image": "images/023_园区轴测图.jpg",
    "customImage": "",
    "duration": 6.0,
    "location": "园区轴测图",
    "method": "3D/MG",
    "shotSize": "轴测大全景",
    "voiceover": "园区规划“两轴十区四中心”空间结构：产业轴集聚全业态，如百川归海；贸易轴打通全球通道，",
    "camera": "固定",
    "description": "【连续画面】1、【三维总平动画】园区轴测总平中，“产业核心集聚轴”作为第一条金色主线由近及远独立延伸，串联产业组团。；2、【三维总平动画】“跨境贸易发展轴”作为第二条金色主线独立亮起并向全球通道方向延伸，与产业轴形成“两轴”结构。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "固定",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-024",
    "id": 24,
    "chapter": "篇章二｜规模定位·时代枢纽",
    "image": "images/024_园区轴测图.jpg",
    "customImage": "",
    "duration": 3.0,
    "location": "园区轴测图",
    "method": "3D/MG",
    "shotSize": "轴测大全景",
    "voiceover": "似巨龙腾飞。全域布局逻辑清晰、功能完备，",
    "camera": "轻俯冲",
    "description": "【三维总平动画】十大交易区按照园区空间顺序逐块点亮，分区色块、建筑轮廓与标签一一对应。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "轻俯冲",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-025",
    "id": 25,
    "chapter": "篇章二｜规模定位·时代枢纽",
    "image": "images/025_园区轴测图 → 总平锁定.jpg",
    "customImage": "",
    "duration": 6.0,
    "location": "园区轴测图 → 总平锁定",
    "method": "3D/MG",
    "shotSize": "轴测大全景 → 超大全景",
    "voiceover": "每一寸土地承载产业梦想，每一条道路通向繁荣远方！",
    "camera": "轻拉远 → 缓拉远",
    "description": "【连续画面】1、【三维总平动画】海关查验、供应链金融、跨境电商、综合服务四大配套中心依次点亮，并与交易区建立节点联系。；2、【三维总平动画】两条发展轴、十大交易区与四大配套中心完整同屏，形成“两轴十区四中心”园区版图总览。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "轻拉远 → 缓拉远",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-026",
    "id": 26,
    "chapter": "篇章三｜业态布局·一站式采购",
    "image": "images/026_生鲜区外部 → 卸货月台.jpg",
    "customImage": "",
    "duration": 5.0,
    "location": "生鲜区外部 → 卸货月台",
    "method": "3D+实拍替代 / 实拍/版权",
    "shotSize": "大全景 → 中景",
    "voiceover": "十大交易区，全品类覆盖：生鲜蔬菜产地直采、杂粮一站式集采；",
    "camera": "低机位跟进 → 侧跟",
    "description": "【连续画面】1、【三维+实拍】生鲜蔬菜交易区卸货月台，一辆满载蔬菜的大车驶入并停靠，交易大厅与繁忙月台在背景中建立空间。；2、【实拍】工人从货车上搬下一筐产地直采蔬菜并放至月台；周围成筐蔬菜码放整齐，保留叉车、货车与人流环境。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "低机位跟进 → 侧跟",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-027",
    "id": 27,
    "chapter": "篇章三｜业态布局·一站式采购",
    "image": "images/027_蔬菜交易大厅.jpg",
    "customImage": "",
    "duration": 3.0,
    "location": "蔬菜交易大厅",
    "method": "实拍/3D",
    "shotSize": "中近景",
    "voiceover": "旁白跨镜延续 / 音乐承接",
    "camera": "小幅推近",
    "description": "【实拍/三维】蔬菜交易大厅内，采购商拿起蔬菜检查品相；前景货品新鲜、后景交易秩序清楚，表现一站式集采。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "小幅推近",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-028",
    "id": 28,
    "chapter": "篇章三｜业态布局·一站式采购",
    "image": "images/028_水果区商铺 → 恒温小冷库.jpg",
    "customImage": "",
    "duration": 3.0,
    "location": "水果区商铺 → 恒温小冷库",
    "method": "3D",
    "shotSize": "中景 → 中近景",
    "voiceover": "进口水果恒温保鲜、前店后仓一体化；旁白跨镜延续 / 音乐承接",
    "camera": "横移 → 推门",
    "description": "【连续画面】1、【三维渲染】进口水果交易区前店后仓商铺立面横向掠过，店招、展示面与后仓入口在同一空间关系中清晰呈现。；2、【三维渲染】分区恒温小冷库门打开，冷气轻涌，内部果箱按品类整齐码放，明确表现进口水果恒温保鲜。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "横移 → 推门",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-029",
    "id": 29,
    "chapter": "篇章三｜业态布局·一站式采购",
    "image": "images/029_鲜果陈列.jpg",
    "customImage": "",
    "duration": 2.0,
    "location": "鲜果陈列",
    "method": "实拍/3D",
    "shotSize": "特写",
    "voiceover": "旁白跨镜延续 / 音乐承接",
    "camera": "微移",
    "description": "【实拍/三维】进口鲜果展厅内，车厘子、榴莲、柑橘等水果精美陈列；以单组主水果近景突出色泽、质感与新鲜度。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "微移",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-030",
    "id": 30,
    "chapter": "篇章三｜业态布局·一站式采购",
    "image": "images/030_冻品冷库外部 → 冻品仓内.jpg",
    "customImage": "",
    "duration": 3.0,
    "location": "冻品冷库外部 → 冻品仓内",
    "method": "3D / 实拍/3D",
    "shotSize": "大全景 → 中景",
    "voiceover": "冻品海产分温区锁鲜，冷链科技赋能；",
    "camera": "低机位前移 → 横滑",
    "description": "【连续画面】1、【三维渲染】低温冷库外立面与冷链装卸月台完整定场，冷库门、车辆泊位与蓝白冷雾共同呈现分温区锁鲜环境。；2、【三维+实拍】冻品仓内，叉车穿梭于低温货架并移出一托盘冻品；货架纵深和包装冻品清晰可见。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "低机位前移 → 横滑",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-031",
    "id": 31,
    "chapter": "篇章三｜业态布局·一站式采购",
    "image": "images/031_鲜活水产大厅.jpg",
    "customImage": "",
    "duration": 2.0,
    "location": "鲜活水产大厅",
    "method": "实拍/3D",
    "shotSize": "特写→中景",
    "voiceover": "旁白跨镜延续 / 音乐承接",
    "camera": "轻推",
    "description": "【三维+实拍】水产鲜活交易大厅，活鱼在透明水箱内游动并跃动水面；以水体反光和鲜活状态表现海产品交易。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "轻推",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "网络图片",
    "sourcePage": "https://www.sohu.com/a/813325360_121123750",
    "sourceNote": "鲜活水产交易市场（网络参考）"
  },
  {
    "uid": "shot-032",
    "id": 32,
    "chapter": "篇章三｜业态布局·一站式采购",
    "image": "images/032_花卉大棚 → 花卉货品.jpg",
    "customImage": "",
    "duration": 5.0,
    "location": "花卉大棚 → 花卉货品",
    "method": "3D/实拍 / 实拍",
    "shotSize": "大全景 → 特写",
    "voiceover": "花卉绿植四季如春，点亮城市诗意。",
    "camera": "稳定器前移 → 微距滑动",
    "description": "【连续画面】1、【三维渲染/实拍】温室花卉展厅大全景，玫瑰、百合与绿植错落有致；通道延伸至画面深处，阳光透过玻璃穹顶洒落。；2、【实拍】单组鲜花或绿植侧逆光微距，花瓣、叶片和水珠纹理清晰，延续“花卉绿植四季如春，点亮城市诗意”的原文意境。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "稳定器前移 → 微距滑动",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-033",
    "id": 33,
    "chapter": "篇章三｜业态布局·一站式采购",
    "image": "images/033_冷链云仓外部 → 立体货架通道.jpg",
    "customImage": "",
    "duration": 3.0,
    "location": "冷链云仓外部 → 立体货架通道",
    "method": "3D / 3D/实拍",
    "shotSize": "超大全景 → 大全景",
    "voiceover": "智慧冷链云仓24小时恒温溯源。旁白跨镜延续 / 音乐承接",
    "camera": "垂直拉升 → 沿通道跟随",
    "description": "【连续画面】1、【三维+实拍】四层智慧冷链云仓全景拉升，建筑、装卸区与冷链车辆完整入画，建立24小时恒温仓储场景。；2、【三维+实拍】智能叉车/AGV沿立体高位货架通道穿梭前进，货位、托盘与纵深形成自动化仓储秩序。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "垂直拉升 → 沿通道跟随",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-034",
    "id": 34,
    "chapter": "篇章三｜业态布局·一站式采购",
    "image": "images/034_温控与溯源.jpg",
    "customImage": "",
    "duration": 2.0,
    "location": "温控与溯源",
    "method": "实拍+UI",
    "shotSize": "特写",
    "voiceover": "旁白跨镜延续 / 音乐承接",
    "camera": "固定",
    "description": "【实拍+UI合成】温度监控大屏数据流动后，工作人员扫描一箱货物的食品溯源二维码，温控与溯源信息同步弹出。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "固定",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-035",
    "id": 35,
    "chapter": "篇章三｜业态布局·一站式采购",
    "image": "images/035_干副粮油区域.jpg",
    "customImage": "",
    "duration": 2.0,
    "location": "干副粮油区域",
    "method": "实拍/3D",
    "shotSize": "中景",
    "voiceover": "国际冷链食品交易区、体验式购物区、进口水果交易区、生鲜食品交易区、食用菌类特菜交易区、花卉交易区、海产品交易区、冷链云仓区、城市集配区、分拣加工区十大特色产品区，",
    "camera": "横移",
    "description": "【实拍/三维】干副粮油交易货位整齐铺陈，粮油、干副产品分类陈列，采购人员从货架通道经过；对应Brief“干副粮油”业态。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "横移",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "网络图片",
    "sourcePage": "https://www.xinghua.gov.cn/xwzx/bmdt/art/2024/art_f7cd7861be274d11a63466d97e56a56e.html",
    "sourceNote": "农产品交易中心粮油专营店（网络参考）"
  },
  {
    "uid": "shot-036",
    "id": 36,
    "chapter": "篇章三｜业态布局·一站式采购",
    "image": "images/036_体验式食品区.jpg",
    "customImage": "",
    "duration": 2.0,
    "location": "体验式食品区",
    "method": "实拍/3D",
    "shotSize": "中近景",
    "voiceover": "城市集配中心从产业中枢直达万家灯火。",
    "camera": "侧跟",
    "description": "【实拍/三维】体验式购物/网红食品区域内，消费者在特色食品陈列前驻足选购，商品展示、试吃与消费场景同框。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "侧跟",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-037",
    "id": 37,
    "chapter": "篇章三｜业态布局·一站式采购",
    "image": "images/037_冷链食品区.jpg",
    "customImage": "",
    "duration": 2.0,
    "location": "冷链食品区",
    "method": "3D/实拍",
    "shotSize": "中景",
    "voiceover": "从田间到餐桌，",
    "camera": "缓推",
    "description": "【三维+实拍】国际冷链食品交易区内，包装冷链食品在专业低温空间分类陈列，冷色环境与温控标识清晰可见。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "缓推",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-038",
    "id": 38,
    "chapter": "篇章三｜业态布局·一站式采购",
    "image": "images/038_菌类特菜.jpg",
    "customImage": "",
    "duration": 2.0,
    "location": "菌类特菜",
    "method": "实拍/3D",
    "shotSize": "特写",
    "voiceover": "一路鲜行——让每一份新鲜，",
    "camera": "小推",
    "description": "【实拍/三维】食用菌类特菜交易区，菌菇与特色蔬菜分品类整齐装筐，近景突出产品纹理与产地直采的新鲜状态。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "小推",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-039",
    "id": 39,
    "chapter": "篇章三｜业态布局·一站式采购",
    "image": "images/039_城市集配调度 → 城市集配出车.jpg",
    "customImage": "",
    "duration": 4.0,
    "location": "城市集配调度 → 城市集配出车",
    "method": "实拍+UI/3D / 实拍/3D",
    "shotSize": "中景 → 大全景",
    "voiceover": "都不负土地的馈赠！旁白跨镜延续 / 音乐承接",
    "camera": "轻推 → 侧跟",
    "description": "【连续画面】1、【实拍+UI/三维】城市集配中心调度席，调度员在配送大屏确认一条任务，屏幕显示线路、车辆与城市配送节点。；2、【实拍/三维】一辆冷链配送车从城市集配中心驶出，车辆由园区产业中枢驶向城区，画面落实“直达万家灯火”。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "轻推 → 侧跟",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-040",
    "id": 40,
    "chapter": "篇章三｜业态布局·一站式采购",
    "image": "images/040_分拣加工区 → 十大交易区总览.jpg",
    "customImage": "",
    "duration": 5.0,
    "location": "分拣加工区 → 十大交易区总览",
    "method": "实拍/3D / 3D/MG",
    "shotSize": "中景 → 轴测大全景",
    "voiceover": "旁白跨镜延续 / 音乐承接",
    "camera": "沿线跟拍 → 拉升",
    "description": "【连续画面】1、【实拍/三维】分拣加工区传送线上，蔬果经过一次自动分级节点并进入对应周转箱，清楚呈现分拣加工流程。；2、【三维+特效包装】园区轴测总览中，国际冷链食品、体验式购物、进口水果、生鲜食品、食用菌类特菜、花卉、海产品、冷链云仓、城市集配、分拣加工十大板块依次亮起并保持。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "沿线跟拍 → 拉升",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-041",
    "id": 41,
    "chapter": "篇章三｜业态布局·一站式采购",
    "image": "images/041_海关查验中心外部 → 智能查验通道.jpg",
    "customImage": "",
    "duration": 4.0,
    "location": "海关查验中心外部 → 智能查验通道",
    "method": "3D / 3D/实拍替代",
    "shotSize": "大全景 → 中景",
    "voiceover": "四大配套中心，全链赋能：海关查验一站式报关放行，",
    "camera": "低机位前移 → 固定",
    "description": "【连续画面】1、【三维】海关查验中心与查验月台大全景，一辆进口冷链货车停在查验位；保税仓储区、通关通道与月台关系清晰。；2、【三维+实拍替代】货物通过智能查验/扫描设备，扫描光线完成一次检测，通关界面同步显示查验信息。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "低机位前移 → 固定",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "网络图片",
    "sourcePage": "https://www.cqn.com.cn/zj/content/2022-11/01/content_8875115.htm",
    "sourceNote": "进口冷链货物监管装车（网络参考）"
  },
  {
    "uid": "shot-042",
    "id": 42,
    "chapter": "篇章三｜业态布局·一站式采购",
    "image": "images/042_通关放行.jpg",
    "customImage": "",
    "duration": 3.0,
    "location": "通关放行",
    "method": "3D/MG",
    "shotSize": "中远景",
    "voiceover": "打通跨境绿色通道；",
    "camera": "跟随出门",
    "description": "【三维+MG】查验完成后闸机绿灯亮起，冷链车辆驶离查验月台，表现“一站式报关放行，打通跨境绿色通道”。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "跟随出门",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-043",
    "id": 43,
    "chapter": "篇章三｜业态布局·一站式采购",
    "image": "images/043_供应链金融中心 → 授信结算界面.jpg",
    "customImage": "",
    "duration": 4.0,
    "location": "供应链金融中心 → 授信结算界面",
    "method": "实拍/3D / 实拍+UI",
    "shotSize": "大全景 → 特写",
    "voiceover": "供应链金融活水浇灌沃土，让奋斗者扎根生长；",
    "camera": "轻推 → 固定",
    "description": "【连续画面】1、【实拍+三维】供应链金融中心商务空间定场，商户与金融工作人员面对面交流，背景保留金融办公大楼或服务柜台环境。；2、【实拍+UI合成】去敏后的授信、结算系统界面完成一次确认，额度、结算与经营数据以简洁动态图形呈现。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "轻推 → 固定",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-044",
    "id": 44,
    "chapter": "篇章三｜业态布局·一站式采购",
    "image": "images/044_商户签约.jpg",
    "customImage": "",
    "duration": 3.0,
    "location": "商户签约",
    "method": "实拍",
    "shotSize": "中近景",
    "voiceover": "旁白跨镜延续 / 音乐承接",
    "camera": "小推",
    "description": "【实拍】商户代表完成签字并与工作人员握手，文件、签字动作与双方表情完整入画，表现供应链金融赋能经营。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "小推",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-045",
    "id": 45,
    "chapter": "篇章三｜业态布局·一站式采购",
    "image": "images/045_跨境电商直播间 → 在线交易数据.jpg",
    "customImage": "",
    "duration": 4.0,
    "location": "跨境电商直播间 → 在线交易数据",
    "method": "实拍 / 实拍+MG",
    "shotSize": "大全景 → 中近景",
    "voiceover": "跨境电商双线融合，开启流通无限可能；",
    "camera": "稳定器进入 → 侧移",
    "description": "【连续画面】1、【实拍】跨境电商直播展厅大全景，主播站在直播台前讲解商品，灯光、商品陈列与拍摄设备共同建立直播场景。；2、【实拍+虚拟包装】主播继续带货，线上全国交易数据大屏与订单数量在侧边实时跳动，表现线上交易增长。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "稳定器进入 → 侧移",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "网络图片",
    "sourcePage": "https://news.hexun.com/2023-08-02/209580123.html",
    "sourceNote": "食品电商直播带货（网络参考）"
  },
  {
    "uid": "shot-046",
    "id": 46,
    "chapter": "篇章三｜业态布局·一站式采购",
    "image": "images/046_包裹分拣.jpg",
    "customImage": "",
    "duration": 3.0,
    "location": "包裹分拣",
    "method": "实拍",
    "shotSize": "中景",
    "voiceover": "旁白跨镜延续 / 音乐承接",
    "camera": "沿线跟拍",
    "description": "【实拍】跨境包裹完成扫码后沿分拣线进入周转箱，打包、传送与分流动作清晰，落实线上线下履约。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "沿线跟拍",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-047",
    "id": 47,
    "chapter": "篇章三｜业态布局·一站式采购",
    "image": "images/047_大数据_溯源中心 → 人才公寓.jpg",
    "customImage": "",
    "duration": 4.0,
    "location": "大数据/溯源中心 → 人才公寓",
    "method": "实拍+MG/3D / 3D/实拍",
    "shotSize": "中景",
    "voiceover": "综合服务集溯源、公寓、商超于一体，全方位守护，",
    "camera": "缓推 → 跟随",
    "description": "【连续画面】1、【实拍+MG/三维】大数据溯源中心内，溯源大屏显示货品来源、温控与流向数据，工作人员背影在前景操作。；2、【三维/实拍】人才公寓大堂，年轻人拖着行李进入并办理入住，体现园区居住配套与人才服务。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "缓推 → 跟随",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-048",
    "id": 48,
    "chapter": "篇章三｜业态布局·一站式采购",
    "image": "images/048_总部办公 → 酒店_商业配套.jpg",
    "customImage": "",
    "duration": 3.5,
    "location": "总部办公 → 酒店/商业配套",
    "method": "实拍/3D",
    "shotSize": "大全景 → 中景",
    "voiceover": "全周期赋能。世界在此无界，",
    "camera": "横移 → 固定",
    "description": "【连续画面】1、【实拍/三维】总部办公空间横向展开，团队正在会议与办公，开放工位、会议区及企业运营状态清晰可见。；2、【实拍/三维】酒店或商超商业配套入口短促定场，门头、顾客与公共空间完整呈现综合服务功能。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "横移 → 固定",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-049",
    "id": 49,
    "chapter": "篇章三｜业态布局·一站式采购",
    "image": "images/049_客服_服务大厅.jpg",
    "customImage": "",
    "duration": 1.5,
    "location": "客服/服务大厅",
    "method": "实拍/3D",
    "shotSize": "中景",
    "voiceover": "机遇在此汇聚！",
    "camera": "轻推",
    "description": "【实拍/三维】客服服务大厅内，服务人员为商户办理一次业务；柜台、办事人员与等候区共同体现全周期服务。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "轻推",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-050",
    "id": 50,
    "chapter": "篇章三｜业态布局·一站式采购",
    "image": "images/050_十大交易区总平 → 四大中心总平.jpg",
    "customImage": "",
    "duration": 4.0,
    "location": "十大交易区总平 → 四大中心总平",
    "method": "3D/MG",
    "shotSize": "轴测大全景",
    "voiceover": "—（音乐主导）",
    "camera": "快速拉升 → 轻拉远",
    "description": "【连续画面】1、【3D/MG混剪】十大交易区总平快速拉升，十个交易板块同时高亮，形成“全品类覆盖”的第一层视觉总结。；2、【3D/MG混剪】四大配套中心节点亮起并与十大交易区连线，数据流在园区内循环，形成“全产业链闭环”。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "快速拉升 → 轻拉远",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-051",
    "id": 51,
    "chapter": "篇章三｜业态布局·一站式采购",
    "image": "images/051_交易大厅人流 → 物流车流.jpg",
    "customImage": "",
    "duration": 4.0,
    "location": "交易大厅人流 → 物流车流",
    "method": "实拍/3D / 3D/实拍",
    "shotSize": "大全景",
    "voiceover": "—（音乐主导）",
    "camera": "稳定器穿行 → 高位固定",
    "description": "【连续画面】1、【实拍/三维混剪】交易大厅内人流、商户与采购人员有序穿行，货品陈列与交易动作共同形成繁忙产业图景。；2、【实拍/三维混剪】多辆冷链货车依次驶出园区，车辆形成连续货流，衔接城市集配与一站式采购成果。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "稳定器穿行 → 高位固定",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-052",
    "id": 52,
    "chapter": "篇章三｜业态布局·一站式采购",
    "image": "images/052_篇章字卡.jpg",
    "customImage": "",
    "duration": 2.0,
    "location": "篇章字卡",
    "method": "MG",
    "shotSize": "全屏",
    "voiceover": "—（音乐主导）",
    "camera": "静态微动",
    "description": "【动态图文】画面由繁忙园区收束至全屏字卡，“全品类覆盖 · 全产业链闭环 · 一站式采购”三组大字依次出现并定格。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "静态微动",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-053",
    "id": 53,
    "chapter": "篇章四｜民生使命·与时代同行",
    "image": "images/053_清晨菜市场 → 社区超市.jpg",
    "customImage": "",
    "duration": 4.0,
    "location": "清晨菜市场 → 社区超市",
    "method": "实拍",
    "shotSize": "大全景 → 中景",
    "voiceover": "立足京津冀大局，打通城乡流通通道，",
    "camera": "稳定器 → 侧跟",
    "description": "【连续画面】1、【实景】天津、北京、河北城乡菜市场清晨开市，摊主打开货车后门并开始卸货，市场灯光与晨雾保留生活质感。；2、【实景】社区超市工作人员将一箱新鲜蔬菜补入货架，货品由周转箱进入零售端，体现城乡流通通道。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "稳定器 → 侧跟",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-054",
    "id": 54,
    "chapter": "篇章四｜民生使命·与时代同行",
    "image": "images/054_菜市场摊位.jpg",
    "customImage": "",
    "duration": 2.0,
    "location": "菜市场摊位",
    "method": "实拍",
    "shotSize": "中近景",
    "voiceover": "稳定“菜篮子、果盘子”物价底线，",
    "camera": "轻推",
    "description": "【实景】老人站在菜市场摊位前，拿起一把蔬菜仔细查看新鲜度；人物手部、表情与货品同框。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "轻推",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "网络图片",
    "sourcePage": "https://xinwen.bjd.com.cn/content/s6727826bd5de417e57f1a8e1.html",
    "sourceNote": "老人菜市场挑选蔬菜（网络参考）"
  },
  {
    "uid": "shot-055",
    "id": 55,
    "chapter": "篇章四｜民生使命·与时代同行",
    "image": "images/055_水果摊.jpg",
    "customImage": "",
    "duration": 2.0,
    "location": "水果摊",
    "method": "实拍",
    "shotSize": "中近景",
    "voiceover": "筑牢民生保障。",
    "camera": "小跟",
    "description": "【实景】水果摊前，孩子双手捧起一个新鲜水果并露出笑容，以人物近景承接“菜篮子、果盘子”的民生温度。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "小跟",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "网络图片",
    "sourcePage": "https://my.nzte.govt.nz/article/singapores-food-and-beverage-retail-sector",
    "sourceNote": "孩子手捧水果微笑（网络参考）"
  },
  {
    "uid": "shot-056",
    "id": 56,
    "chapter": "篇章四｜民生使命·与时代同行",
    "image": "images/056_家庭厨房 → 家庭餐桌.jpg",
    "customImage": "",
    "duration": 4.0,
    "location": "家庭厨房 → 家庭餐桌",
    "method": "实拍",
    "shotSize": "特写 → 中景",
    "voiceover": "这是沉甸甸的承诺，是千万家庭餐桌上的幸福与安心！",
    "camera": "固定 → 缓推",
    "description": "【连续画面】1、【实景】家庭厨房内，洗净蔬菜入锅，蒸汽从锅中升起并充满前景，由市场流通自然落到家庭餐桌。；2、【实景】一家人围坐在热气腾腾的餐桌旁自然交流、用餐，完成“千万家庭餐桌上的幸福与安心”的具体落点。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "固定 → 缓推",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-057",
    "id": 57,
    "chapter": "篇章四｜民生使命·与时代同行",
    "image": "images/057_天津港码头 → 港区道路.jpg",
    "customImage": "",
    "duration": 4.0,
    "location": "天津港码头 → 港区道路",
    "method": "实拍/版权 / 实拍/3D",
    "shotSize": "大全景 → 中远景",
    "voiceover": "践行港产城深度融合，以港口聚产业、以产业兴城市、以城市强港口——三位一体，",
    "camera": "固定 → 侧跟",
    "description": "【连续画面】1、【实拍/版权】天津港码头桥吊将一个集装箱落到运输车，吊装动作完整结束，开启“港—产—城”物流动线。；2、【实拍/三维】装载集装箱的货车从港区道路驶出，港口设施留在背景，表现“以港口聚产业”。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "固定 → 侧跟",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "网络图片",
    "sourcePage": "https://tradeinservices.mofcom.gov.cn/article/news/tpxw/tupian/202003/100891.html",
    "sourceNote": "天津港港区集装箱卡车（网络参考）"
  },
  {
    "uid": "shot-058",
    "id": 58,
    "chapter": "篇章四｜民生使命·与时代同行",
    "image": "images/058_园区入口.jpg",
    "customImage": "",
    "duration": 2.0,
    "location": "园区入口",
    "method": "3D",
    "shotSize": "大全景",
    "voiceover": "同频共振，",
    "camera": "低机位跟随",
    "description": "【三维】同类车辆沿主路进入园区入口，门头与产业建筑同时入画，将港口货流导入项目。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "低机位跟随",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-059",
    "id": 59,
    "chapter": "篇章四｜民生使命·与时代同行",
    "image": "images/059_分拣加工区.jpg",
    "customImage": "",
    "duration": 2.0,
    "location": "分拣加工区",
    "method": "实拍/3D",
    "shotSize": "中景",
    "voiceover": "构建全国标杆。",
    "camera": "沿线跟",
    "description": "【实拍/三维】货物进入加工分拣线并完成一次分流，传送带与分级节点表现“以产业兴城市”的加工环节。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "沿线跟",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-060",
    "id": 60,
    "chapter": "篇章四｜民生使命·与时代同行",
    "image": "images/060_城市集配中心 → 天津城市网络.jpg",
    "customImage": "",
    "duration": 4.0,
    "location": "城市集配中心 → 天津城市网络",
    "method": "3D/实拍 / MG/三维地图",
    "shotSize": "大全景 → 俯视大全景",
    "voiceover": "↳旁白跨镜延续 / 音乐承接旁白跨镜延续 / 音乐承接",
    "camera": "高位固定 → 地图拉升",
    "description": "【连续画面】1、【三维/实拍】冷链配送车从城市集配中心驶出，车辆整齐发车，货物流由园区转入城市配送。；2、【三维地图】天津城区配送网络从项目节点向外逐个点亮，最终形成“港口→园区→城市”的动态光流线路。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "高位固定 → 地图拉升",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-061",
    "id": 61,
    "chapter": "篇章四｜民生使命·与时代同行",
    "image": "images/061_全球地图 → 一带一路线路.jpg",
    "customImage": "",
    "duration": 4.0,
    "location": "全球地图 → 一带一路线路",
    "method": "3D/MG",
    "shotSize": "全球大全景",
    "voiceover": "深度融入国内国际双循环，链接“一带一路”与中蒙俄走廊，",
    "camera": "地球旋转 → 沿线追踪",
    "description": "【连续画面】1、【虚拟全球地图】地球旋转至东亚，天津节点首先亮起，国内与国际两组流通方向在画面中建立。；2、【虚拟全球地图】从天津向外延伸“一带一路”示意线路，沿线节点依次点亮，形成对外贸易主通道。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "地球旋转 → 沿线追踪",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-062",
    "id": 62,
    "chapter": "篇章四｜民生使命·与时代同行",
    "image": "images/062_中蒙俄经济走廊.jpg",
    "customImage": "",
    "duration": 2.0,
    "location": "中蒙俄经济走廊",
    "method": "3D/MG",
    "shotSize": "区域大全景",
    "voiceover": "进口全球优质生鲜，",
    "camera": "北向追踪",
    "description": "【虚拟全球地图】中蒙俄经济走廊方向独立发光，高亮天津与蒙古、俄罗斯之间的北向连接。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "北向追踪",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-063",
    "id": 63,
    "chapter": "篇章四｜民生使命·与时代同行",
    "image": "images/063_中欧班列.jpg",
    "customImage": "",
    "duration": 2.0,
    "location": "中欧班列",
    "method": "实拍/版权+MG",
    "shotSize": "远景",
    "voiceover": "输出天津特色农产。",
    "camera": "长焦跟随",
    "description": "【实拍/版权+MG】中欧班列货运列车横向穿过画面，铁路沿线叠加轻量光流，表现陆路国际通道。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "长焦跟随",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "网络图片",
    "sourcePage": "https://news.jstv.com/a/20220724/1658671175677.shtml",
    "sourceNote": "中欧班列货运列车（网络参考）"
  },
  {
    "uid": "shot-064",
    "id": 64,
    "chapter": "篇章四｜民生使命·与时代同行",
    "image": "images/064_全球生鲜汇聚天津 → 天津农产走向世界.jpg",
    "customImage": "",
    "duration": 6.0,
    "location": "全球生鲜汇聚天津 → 天津农产走向世界",
    "method": "3D/MG",
    "shotSize": "全球→天津 → 天津→全球",
    "voiceover": "双向奔赴，互利共赢，彰显大国枢纽的胸怀与担当！",
    "camera": "线路收拢 → 线路扩散",
    "description": "【连续画面】1、【虚拟全球地图】海运航线与海外光线从世界各地汇聚天津，生鲜货品图形随线路进入，表现进口全球优质生鲜。；2、【虚拟全球地图】光线由天津向全球反向延伸，天津特色农产品沿线路输出，进口与出口共同形成双向流通。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "线路收拢 → 线路扩散",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-065",
    "id": 65,
    "chapter": "篇章四｜民生使命·与时代同行",
    "image": "images/065_商户装车 → 市民选购.jpg",
    "customImage": "",
    "duration": 4.0,
    "location": "商户装车 → 市民选购",
    "method": "实拍",
    "shotSize": "中景 → 中近景",
    "voiceover": "产业价值与民生温度共生共存。我们不仅建造一座市场，",
    "camera": "侧跟 → 轻推",
    "description": "【连续画面】1、【实拍】商户清晨完成装车，关上满载货物的车门并露出笑容，人物与经营车辆共同呈现产业人的日常。；2、【实拍】市民挑选商品后满意点头，与摊主完成简短交流，表现市场交易中的信任与生活温度。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "侧跟 → 轻推",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-066",
    "id": 66,
    "chapter": "篇章四｜民生使命·与时代同行",
    "image": "images/066_人才公寓入住.jpg",
    "customImage": "",
    "duration": 2.0,
    "location": "人才公寓入住",
    "method": "实拍/3D",
    "shotSize": "中景",
    "voiceover": "更守护一种生活；不仅追求一份业绩，",
    "camera": "跟拍",
    "description": "【实拍/三维】人才公寓门前，年轻人拎包或拖行李刷卡进入，体现园区对奋斗者工作与生活的承载。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "跟拍",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "网络图片",
    "sourcePage": "https://www.sabeeapp.com/tm30",
    "sourceNote": "年轻职业人士携行李进入现代大堂（网络参考）"
  },
  {
    "uid": "shot-067",
    "id": 67,
    "chapter": "篇章四｜民生使命·与时代同行",
    "image": "images/067_园区食堂.jpg",
    "customImage": "",
    "duration": 2.0,
    "location": "园区食堂",
    "method": "实拍/3D",
    "shotSize": "中景",
    "voiceover": "更传递一份温情。",
    "camera": "固定",
    "description": "【实拍/三维】园区食堂内，用餐者坐下并端起热汤或饭菜；热气、餐桌与安心神态构成温情画面。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "固定",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-068",
    "id": 68,
    "chapter": "篇章四｜民生使命·与时代同行",
    "image": "images/068_园区夕阳 → 园区灯火初上.jpg",
    "customImage": "",
    "duration": 4.0,
    "location": "园区夕阳 → 园区灯火初上",
    "method": "3D",
    "shotSize": "超大全景 → 大全景",
    "voiceover": "这是产业人的初心，更是奋斗者的荣光！",
    "camera": "延时 → 缓拉升",
    "description": "【连续画面】1、【3D渲染】夕阳下园区由金色时刻进入蓝调时刻，道路、建筑与天空层次缓慢变化。；2、【3D渲染】园区灯火初上，第一批建筑与道路灯光依次亮起，暖黄色灯光在暮色中形成“初心 · 荣光”收束。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "延时 → 缓拉升",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-069",
    "id": 69,
    "chapter": "篇章五｜未来可期·共赢未来",
    "image": "images/069_园区黄昏 → 建筑灯光.jpg",
    "customImage": "",
    "duration": 4.0,
    "location": "园区黄昏 → 建筑灯光",
    "method": "3D",
    "shotSize": "超大全景 → 大全景",
    "voiceover": "未来，这里将形成千亿级跨境农产品产业集群，成为滨海新区全新经济增长极。",
    "camera": "固定延时 → 固定",
    "description": "【连续画面】1、【4K 3D渲染】黄昏时分园区全景稳定呈现，天空由暖金进入蓝调，产业新城轮廓完整铺开。；2、【4K 3D渲染】交易区、冷库与配套建筑灯火由近到远次第点亮，园区夜间运营空间逐层显现。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "固定延时 → 固定",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-070",
    "id": 70,
    "chapter": "篇章五｜未来可期·共赢未来",
    "image": "images/070_园区车流.jpg",
    "customImage": "",
    "duration": 2.0,
    "location": "园区车流",
    "method": "3D",
    "shotSize": "高位大全景",
    "voiceover": "千亿宏图，",
    "camera": "高位横移",
    "description": "【4K 3D渲染】园区主路车流如织，冷链车辆灯光形成连续光点，商铺通明并呈现繁华运营状态。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "高位横移",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-071",
    "id": 71,
    "chapter": "篇章五｜未来可期·共赢未来",
    "image": "images/071_交易大厅未来运营.jpg",
    "customImage": "",
    "duration": 3.0,
    "location": "交易大厅未来运营",
    "method": "3D/实拍合成",
    "shotSize": "大全景",
    "voiceover": "在此铺展；万千机遇，在此汇聚；一座产业新城，",
    "camera": "缓推",
    "description": "【4K 3D/实拍合成】交易大厅内人流涌动，商户、采购人员与货物流有序运行，表现项目全面建成后的繁华景象。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "缓推",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-072",
    "id": 72,
    "chapter": "篇章五｜未来可期·共赢未来",
    "image": "images/072_产业新城鸟瞰.jpg",
    "customImage": "",
    "duration": 3.0,
    "location": "产业新城鸟瞰",
    "method": "3D",
    "shotSize": "超大全景",
    "voiceover": "正蓄势待发，即将喷薄而出！",
    "camera": "航拍拉升",
    "description": "【4K 3D渲染】航拍继续拉升，整片园区与滨海新区城市灯光共同入画，产业新城在暮色中璀璨如星河。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "航拍拉升",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-073",
    "id": 73,
    "chapter": "篇章五｜未来可期·共赢未来",
    "image": "images/073_项目调研现场.jpg",
    "customImage": "",
    "duration": 2.0,
    "location": "项目调研现场",
    "method": "实拍",
    "shotSize": "中景",
    "voiceover": "作为京津冀协同、港产城融合双示范项目，",
    "camera": "侧跟",
    "description": "【实拍】政府考察团在项目现场边行走边听讲解，调研人员、讲解者与项目背景同框，表现政企调研交流。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "侧跟",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-074",
    "id": 74,
    "chapter": "篇章五｜未来可期·共赢未来",
    "image": "images/074_签约现场.jpg",
    "customImage": "",
    "duration": 2.0,
    "location": "签约现场",
    "method": "实拍",
    "shotSize": "中近景",
    "voiceover": "依托天津港临港优势与首衡全国供应链网络，",
    "camera": "固定",
    "description": "【实拍】商户代表完成签约后交换文件并握手，现场掌声与双方表情完整呈现合作落地。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "固定",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-075",
    "id": 75,
    "chapter": "篇章五｜未来可期·共赢未来",
    "image": "images/075_贸易洽谈.jpg",
    "customImage": "",
    "duration": 2.0,
    "location": "贸易洽谈",
    "method": "实拍",
    "shotSize": "中景",
    "voiceover": "打造北方进出口农产品贸易新高地。双示范引领，",
    "camera": "缓横移",
    "description": "【实拍】国内外贸易商围桌洽谈或举杯交流，项目资料与园区沙盘位于画面内，表现全球贸易合作。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "缓横移",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "网络图片",
    "sourcePage": "https://www.worldjournal.com/wj/story/121339/8623232?zh-cn",
    "sourceNote": "中外商务人士正式会谈（网络参考）"
  },
  {
    "uid": "shot-076",
    "id": 76,
    "chapter": "篇章五｜未来可期·共赢未来",
    "image": "images/076_全球伙伴视频连线 → 合作伙伴群像.jpg",
    "customImage": "",
    "duration": 4.0,
    "location": "全球伙伴视频连线 → 合作伙伴群像",
    "method": "实拍+屏幕合成 / 实拍",
    "shotSize": "中景 → 中近景",
    "voiceover": "双优势叠加，我们站立在北方开放最前沿，向世界发出天津的最强音！",
    "camera": "小推 → 慢横移",
    "description": "【连续画面】1、【实拍+屏幕合成】会议屏幕显示多地全球合作伙伴视频连线，现场人员面向屏幕交流，建立跨区域协作。；2、【实拍】政府、商户、贸易伙伴与企业代表自然交流形成笑脸群像，视线最终统一朝向项目沙盘或园区大屏。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "小推 → 慢横移",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-077",
    "id": 77,
    "chapter": "篇章五｜未来可期·共赢未来",
    "image": "images/077_园区主路 → 项目主入口.jpg",
    "customImage": "",
    "duration": 4.0,
    "location": "园区主路 → 项目主入口",
    "method": "3D",
    "shotSize": "大全景",
    "voiceover": "立足时代风口，共启产业新篇！天津国际农产品交易中心，",
    "camera": "快速稳定前穿 → 减速推近",
    "description": "【连续画面】1、【三维】镜头高速穿越繁华园区主路，交易大厅、冷库、物流车辆与城市灯光从两侧掠过，向主入口方向推进。；2、【三维】镜头在项目主入口大门前减速并缓缓推近，门头标识、建筑材质与园区灯光稳定进入完整构图。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "快速稳定前穿 → 减速推近",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-078",
    "id": 78,
    "chapter": "篇章五｜未来可期·共赢未来",
    "image": "images/078_项目LOGO_名称.jpg",
    "customImage": "",
    "duration": 2.0,
    "location": "项目LOGO/名称",
    "method": "MG",
    "shotSize": "全屏",
    "voiceover": "诚邀政府、商户、金融机构、全球贸易伙伴携手同行。",
    "camera": "光线汇聚",
    "description": "【三维+MG】园区背景压暗，金色光芒汇聚，项目LOGO与“天津国际农产品交易中心”名称全屏中央定格。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "光线汇聚",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-079",
    "id": 79,
    "chapter": "篇章五｜未来可期·共赢未来",
    "image": "images/079_招商信息页1 → 招商信息页2.jpg",
    "customImage": "",
    "duration": 6.0,
    "location": "招商信息页1 → 招商信息页2",
    "method": "MG",
    "shotSize": "全屏",
    "voiceover": "让我们以梦想为帆，以实干为桨，",
    "camera": "静态微动",
    "description": "【连续画面】1、【动态图文定版】招商合作热线作为主信息单独浮现，保留项目LOGO与统一金色视觉体系；具体号码留作可替换字段。；2、【动态图文定版】项目地址作为主信息单独浮现，版式与招商热线页连续统一；具体地址留作可替换字段。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "静态微动",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  },
  {
    "uid": "shot-080",
    "id": 80,
    "chapter": "篇章五｜未来可期·共赢未来",
    "image": "images/080_联合打造页 → 最终Slogan.jpg",
    "customImage": "",
    "duration": 6.0,
    "location": "联合打造页 → 最终Slogan",
    "method": "MG",
    "shotSize": "全屏",
    "voiceover": "在这片充满希望的热土上——共赢千亿产业未来，共铸时代不朽丰碑！",
    "camera": "稳态定格 → 粒子轻聚",
    "description": "【连续画面】1、【品牌定版】天津食品集团与首衡集团双LOGO并列，项目名称同屏，完整呈现“天津食品集团 × 首衡集团 联合打造”。；2、【最终定版】全屏金色粒子与潮线汇聚成Slogan“共赢千亿产业未来 · 共铸时代不朽丰碑”，完整定格后渐黑。",
    "sound": "旁白 + 环境音",
    "angle": "",
    "movement": "稳态定格 → 粒子轻聚",
    "equipment": "待定",
    "focal": "待定",
    "sourceType": "参考视频截帧",
    "sourcePage": "",
    "sourceNote": "允许保留原视频水印；按已核对抽帧序列匹配，原MP4直接跳转可能存在时间轴偏移"
  }
];
