"""create_initial_tables

Revision ID: fdc1353e5b23
Revises: 
Create Date: 2026-09-29 03:08:38.480414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdc1353e5b23'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('productions',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('template_type', sa.String(length=64), nullable=False),
    sa.Column('fps_num', sa.Integer(), nullable=False),
    sa.Column('fps_den', sa.Integer(), nullable=False),
    sa.Column('drop_frame', sa.Boolean(), nullable=False),
    sa.Column('start_timecode_frames', sa.BigInteger(), nullable=False),
    sa.Column('target_duration_frames', sa.BigInteger(), nullable=True),
    sa.Column('aspect_ratio', sa.String(length=32), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_productions'))
    )
    with op.batch_alter_table('productions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_productions_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_productions_name'), ['name'], unique=False)

    op.create_table('roles',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=True)

    op.create_table('assets',
    sa.Column('production_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('asset_type', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('proxy_storage_key', sa.String(length=512), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_frames', sa.BigInteger(), nullable=True),
    sa.Column('fps_num', sa.Integer(), nullable=True),
    sa.Column('fps_den', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('hash_sha256', sa.String(length=64), nullable=False),
    sa.Column('rights_status', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['production_id'], ['productions.id'], name=op.f('fk_assets_production_id_productions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_assets_storage_key'))
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_asset_type'), ['asset_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_production_id'), ['production_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_source_type'), ['source_type'], unique=False)

    op.create_table('exports',
    sa.Column('production_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['production_id'], ['productions.id'], name=op.f('fk_exports_production_id_productions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exports'))
    )
    with op.batch_alter_table('exports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exports_production_id'), ['production_id'], unique=False)

    op.create_table('sequences',
    sa.Column('production_id', sa.String(), nullable=False),
    sa.Column('display_number', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sort_index', sa.Float(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['production_id'], ['productions.id'], name=op.f('fk_sequences_production_id_productions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sequences'))
    )
    with op.batch_alter_table('sequences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sequences_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sequences_production_id'), ['production_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sequences_sort_index'), ['sort_index'], unique=False)

    op.create_table('shares',
    sa.Column('production_id', sa.String(), nullable=False),
    sa.Column('snapshot_id', sa.String(length=64), nullable=True),
    sa.Column('snapshot_json', sa.JSON(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('allow_download', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['production_id'], ['productions.id'], name=op.f('fk_shares_production_id_productions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shares'))
    )
    with op.batch_alter_table('shares', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shares_production_id'), ['production_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shares_token_hash'), ['token_hash'], unique=True)

    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('asset_versions',
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('hash_sha256', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_asset_versions_asset_id_assets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_versions'))
    )
    with op.batch_alter_table('asset_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_versions_asset_id'), ['asset_id'], unique=False)

    op.create_table('scenes',
    sa.Column('production_id', sa.String(), nullable=False),
    sa.Column('sequence_id', sa.String(), nullable=False),
    sa.Column('display_number', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('int_ext', sa.String(length=32), nullable=True),
    sa.Column('day_night', sa.String(length=32), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sort_index', sa.Float(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['production_id'], ['productions.id'], name=op.f('fk_scenes_production_id_productions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sequence_id'], ['sequences.id'], name=op.f('fk_scenes_sequence_id_sequences'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenes'))
    )
    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenes_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scenes_production_id'), ['production_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scenes_sequence_id'), ['sequence_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scenes_sort_index'), ['sort_index'], unique=False)

    op.create_table('stock_asset_metadata',
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(length=128), nullable=False),
    sa.Column('provider_asset_id', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('price', sa.Double(), nullable=True),
    sa.Column('currency', sa.String(length=16), nullable=True),
    sa.Column('license_type', sa.String(length=64), nullable=True),
    sa.Column('territory', sa.String(length=128), nullable=True),
    sa.Column('platforms', sa.JSON(), nullable=False),
    sa.Column('purchase_status', sa.String(length=64), nullable=False),
    sa.Column('contract_reference', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_stock_asset_metadata_asset_id_assets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_asset_metadata'))
    )
    with op.batch_alter_table('stock_asset_metadata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_asset_metadata_asset_id'), ['asset_id'], unique=False)

    op.create_table('shots',
    sa.Column('production_id', sa.String(), nullable=False),
    sa.Column('sequence_id', sa.String(), nullable=True),
    sa.Column('scene_id', sa.String(), nullable=True),
    sa.Column('display_number', sa.String(length=64), nullable=False),
    sa.Column('sort_index', sa.Float(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('performance', sa.Text(), nullable=False),
    sa.Column('composition', sa.Text(), nullable=False),
    sa.Column('director_notes', sa.Text(), nullable=False),
    sa.Column('duration_frames', sa.BigInteger(), nullable=False),
    sa.Column('timing_locked', sa.Boolean(), nullable=False),
    sa.Column('shot_size', sa.String(length=64), nullable=True),
    sa.Column('camera_angle', sa.String(length=64), nullable=True),
    sa.Column('camera_height', sa.String(length=64), nullable=True),
    sa.Column('lens_mm', sa.Float(), nullable=True),
    sa.Column('camera', sa.String(length=128), nullable=True),
    sa.Column('sensor', sa.String(length=64), nullable=True),
    sa.Column('aperture', sa.String(length=32), nullable=True),
    sa.Column('shutter', sa.String(length=32), nullable=True),
    sa.Column('camera_movement', sa.JSON(), nullable=False),
    sa.Column('dialogue', sa.Text(), nullable=False),
    sa.Column('voice_over', sa.Text(), nullable=False),
    sa.Column('subtitle', sa.Text(), nullable=False),
    sa.Column('music_notes', sa.Text(), nullable=False),
    sa.Column('sfx_notes', sa.Text(), nullable=False),
    sa.Column('primary_method', sa.String(length=64), nullable=False),
    sa.Column('secondary_methods', sa.JSON(), nullable=False),
    sa.Column('department', sa.String(length=64), nullable=True),
    sa.Column('owner_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('approval_status', sa.String(length=64), nullable=False),
    sa.Column('vfx_required', sa.Boolean(), nullable=False),
    sa.Column('continuity_notes', sa.Text(), nullable=False),
    sa.Column('risk_notes', sa.Text(), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['production_id'], ['productions.id'], name=op.f('fk_shots_production_id_productions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], name=op.f('fk_shots_scene_id_scenes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sequence_id'], ['sequences.id'], name=op.f('fk_shots_sequence_id_sequences'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shots'))
    )
    with op.batch_alter_table('shots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shots_approval_status'), ['approval_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_shots_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_shots_department'), ['department'], unique=False)
        batch_op.create_index(batch_op.f('ix_shots_display_number'), ['display_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_shots_primary_method'), ['primary_method'], unique=False)
        batch_op.create_index(batch_op.f('ix_shots_production_id'), ['production_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shots_scene_id'), ['scene_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shots_sequence_id'), ['sequence_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shots_sort_index'), ['sort_index'], unique=False)
        batch_op.create_index(batch_op.f('ix_shots_status'), ['status'], unique=False)

    op.create_table('approvals',
    sa.Column('shot_id', sa.String(), nullable=False),
    sa.Column('shot_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shot_id'], ['shots.id'], name=op.f('fk_approvals_shot_id_shots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approvals'))
    )
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approvals_shot_id'), ['shot_id'], unique=False)

    op.create_table('client_asset_requests',
    sa.Column('shot_id', sa.String(), nullable=False),
    sa.Column('requested_from', sa.String(length=255), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shot_id'], ['shots.id'], name=op.f('fk_client_asset_requests_shot_id_shots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_asset_requests'))
    )
    with op.batch_alter_table('client_asset_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_asset_requests_shot_id'), ['shot_id'], unique=False)

    op.create_table('comments',
    sa.Column('production_id', sa.String(), nullable=False),
    sa.Column('shot_id', sa.String(), nullable=True),
    sa.Column('asset_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_comments_asset_id_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['production_id'], ['productions.id'], name=op.f('fk_comments_production_id_productions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shot_id'], ['shots.id'], name=op.f('fk_comments_shot_id_shots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comments'))
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_production_id'), ['production_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_shot_id'), ['shot_id'], unique=False)

    op.create_table('panels',
    sa.Column('shot_id', sa.String(), nullable=False),
    sa.Column('display_number', sa.String(length=64), nullable=False),
    sa.Column('sort_index', sa.Float(), nullable=False),
    sa.Column('asset_id', sa.String(length=64), nullable=True),
    sa.Column('duration_frames', sa.BigInteger(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shot_id'], ['shots.id'], name=op.f('fk_panels_shot_id_shots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_panels'))
    )
    with op.batch_alter_table('panels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_panels_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_panels_shot_id'), ['shot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_panels_sort_index'), ['sort_index'], unique=False)

    op.create_table('production_steps',
    sa.Column('shot_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('department', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('sort_index', sa.Float(), nullable=False),
    sa.Column('input_asset_id', sa.String(length=64), nullable=True),
    sa.Column('output_asset_id', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shot_id'], ['shots.id'], name=op.f('fk_production_steps_shot_id_shots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_production_steps'))
    )
    with op.batch_alter_table('production_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_production_steps_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_steps_shot_id'), ['shot_id'], unique=False)

    op.create_table('shot_asset_links',
    sa.Column('shot_id', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_shot_asset_links_asset_id_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shot_id'], ['shots.id'], name=op.f('fk_shot_asset_links_shot_id_shots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shot_asset_links'))
    )
    with op.batch_alter_table('shot_asset_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shot_asset_links_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shot_asset_links_shot_id'), ['shot_id'], unique=False)

    op.create_table('shot_versions',
    sa.Column('shot_id', sa.String(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shot_id'], ['shots.id'], name=op.f('fk_shot_versions_shot_id_shots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shot_versions'))
    )
    with op.batch_alter_table('shot_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shot_versions_shot_id'), ['shot_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shot_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shot_versions_shot_id'))

    op.drop_table('shot_versions')
    with op.batch_alter_table('shot_asset_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shot_asset_links_shot_id'))
        batch_op.drop_index(batch_op.f('ix_shot_asset_links_asset_id'))

    op.drop_table('shot_asset_links')
    with op.batch_alter_table('production_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_steps_shot_id'))
        batch_op.drop_index(batch_op.f('ix_production_steps_deleted_at'))

    op.drop_table('production_steps')
    with op.batch_alter_table('panels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_panels_sort_index'))
        batch_op.drop_index(batch_op.f('ix_panels_shot_id'))
        batch_op.drop_index(batch_op.f('ix_panels_deleted_at'))

    op.drop_table('panels')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_shot_id'))
        batch_op.drop_index(batch_op.f('ix_comments_production_id'))
        batch_op.drop_index(batch_op.f('ix_comments_deleted_at'))

    op.drop_table('comments')
    with op.batch_alter_table('client_asset_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_asset_requests_shot_id'))

    op.drop_table('client_asset_requests')
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approvals_shot_id'))

    op.drop_table('approvals')
    with op.batch_alter_table('shots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shots_status'))
        batch_op.drop_index(batch_op.f('ix_shots_sort_index'))
        batch_op.drop_index(batch_op.f('ix_shots_sequence_id'))
        batch_op.drop_index(batch_op.f('ix_shots_scene_id'))
        batch_op.drop_index(batch_op.f('ix_shots_production_id'))
        batch_op.drop_index(batch_op.f('ix_shots_primary_method'))
        batch_op.drop_index(batch_op.f('ix_shots_display_number'))
        batch_op.drop_index(batch_op.f('ix_shots_department'))
        batch_op.drop_index(batch_op.f('ix_shots_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_shots_approval_status'))

    op.drop_table('shots')
    with op.batch_alter_table('stock_asset_metadata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_asset_metadata_asset_id'))

    op.drop_table('stock_asset_metadata')
    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenes_sort_index'))
        batch_op.drop_index(batch_op.f('ix_scenes_sequence_id'))
        batch_op.drop_index(batch_op.f('ix_scenes_production_id'))
        batch_op.drop_index(batch_op.f('ix_scenes_deleted_at'))

    op.drop_table('scenes')
    with op.batch_alter_table('asset_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_versions_asset_id'))

    op.drop_table('asset_versions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('shares', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shares_token_hash'))
        batch_op.drop_index(batch_op.f('ix_shares_production_id'))

    op.drop_table('shares')
    with op.batch_alter_table('sequences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sequences_sort_index'))
        batch_op.drop_index(batch_op.f('ix_sequences_production_id'))
        batch_op.drop_index(batch_op.f('ix_sequences_deleted_at'))

    op.drop_table('sequences')
    with op.batch_alter_table('exports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exports_production_id'))

    op.drop_table('exports')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_source_type'))
        batch_op.drop_index(batch_op.f('ix_assets_production_id'))
        batch_op.drop_index(batch_op.f('ix_assets_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_assets_asset_type'))

    op.drop_table('assets')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_name'))

    op.drop_table('roles')
    with op.batch_alter_table('productions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_productions_name'))
        batch_op.drop_index(batch_op.f('ix_productions_deleted_at'))

    op.drop_table('productions')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
